-- Bootstrap only: does not replace or alter existing tables.
create table if not exists public.sensor_data (
  id bigint generated by default as identity primary key,
  device_id text not null,
  sensor_index int not null check (sensor_index >= 0),
  temperature_c numeric not null check (temperature_c between -55 and 125),
  timestamp timestamptz not null
);
create table if not exists public.device_permissions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id text not null,
  sensor_index int not null check (sensor_index >= 0)
);
create table if not exists public.sensor_names (
  device_id text not null,
  sensor_index int not null check (sensor_index >= 0),
  name text not null,
  updated_at timestamptz not null default now(),
  primary key (device_id, sensor_index)
);
create table if not exists public.hvac_events (
  id uuid primary key default gen_random_uuid(),
  device_id text not null,
  sensor_index int not null check (sensor_index >= 0),
  event_type text not null check (event_type = 'setback'),
  occurred_at timestamptz not null,
  amplitude_f numeric,
  duration_minutes numeric,
  typical_amplitude_f numeric,
  created_at timestamptz not null default now(),
  unique (device_id, sensor_index, event_type, occurred_at)
);
create table if not exists public.alert_rules (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id text not null,
  sensor_index int not null check (sensor_index >= 0),
  high_f numeric,
  low_f numeric,
  enabled boolean not null default true,
  is_triggered boolean not null default false,
  last_notified_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, device_id, sensor_index),
  constraint alert_rules_threshold_required check (high_f is not null or low_f is not null)
);
grant all on public.sensor_data, public.device_permissions, public.sensor_names,
  public.hvac_events, public.alert_rules to service_role;
do $$
declare sensor_sequence text;
begin
  if exists (select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'sensor_data' and column_name = 'id') then
    sensor_sequence := pg_get_serial_sequence('public.sensor_data', 'id');
    if sensor_sequence is not null then
      execute format('grant usage, select on sequence %s to service_role', sensor_sequence);
    end if;
  end if;
end $$;
alter table public.sensor_data enable row level security;
alter table public.device_permissions enable row level security;
alter table public.sensor_names enable row level security;
alter table public.alert_rules enable row level security;
alter table public.hvac_events enable row level security;
